id: P004223
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:02:35.232967
source_metadata:
  id: bdr:W27312
  title: ལམ་གྱི་གཙོ་བོ་རྣམ་གསུམ
  author: ''
  volumes:
    e2209b1ad6a848e9a9b78ea7bc6004dc:
      image_group_id: I1PD36263
      title: ''
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
