id: I2CAECE6C
legacy_id: P004223
ocr_import_info:
  bdrc_scan_id: W27312
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T12:26:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:11:53.287380+00:00'
last_modified: 2022-09-02 15:12:00.550575
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27312
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27312
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་གྱི་གཙོ་བོ་རྣམ་གསུམ།
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7236585389080692
  ocr_word_median_confidence_index: 0.875
quality: null
bases:
  I1PD36263:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD36263
      total_pages: 10
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD36263.txt
    statistics:
      ocr_word_median_confidence_index: 0.875
      ocr_word_mean_confidence_index: 0.7236585389080692
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
