id: I2CAECE6C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:27:06+00:00'
last_modified: '2022-06-07T21:11:59.536505+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27312
  title: ལམ་གྱི་གཙོ་བོ་རྣམ་གསུམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DD31:
      image_group_id: I1PD36263
      title: ''
      total_pages: 10
      order: 1
      base_file: DD31.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
